apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-sso-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: klodpler-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: auth.jri.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
